# Generated by Django 4.2.4 on 2023-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nomi')),
                ('value', models.FloatField(default=0, verbose_name='narxi')),
                ('description', models.TextField(verbose_name="Ta'rifi")),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('img', models.ImageField(upload_to='product', verbose_name='rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
    ]
